<?php
return [
    'dbase'=>[
    'master_slave'=>false,//开启数据库主从
    'localhost_read'=>[
        'host'=>'xxx',
        'user'=>'root',
        'pass'=>'xxx',
        'data'=>'test',
        'prefix'=>'wx_'
    ],
    'localhost_write'=>[
        'host'=>'xxx',
        'user'=>'root',
        'pass'=>'xxx',
        'data'=>'test',
        'prefix'=>'wx_'
    ],
    ]
];